# Generated by Django 5.2 on 2026-07-07 15:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='province',
            field=models.CharField(db_index=True, default='Tehran', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('medical_staff', 'Medical staff'), ('admin', 'Admin')], max_length=32),
        ),
        migrations.CreateModel(
            name='MedicalCenterAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='accounts.medicalcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('national_code', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='National code must contain exactly 10 digits.', regex='^\\d{10}$')])),
                ('mobile_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian mobile number.', regex='^09\\d{9}$')])),
                ('password_hash', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registration_requests', to='accounts.medicalcenter')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('national_code',), name='unique_pending_staff_request_national_code'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('mobile_number',), name='unique_pending_staff_request_mobile_number')],
            },
        ),
    ]
