# Generated by Django 5.2 on 2026-07-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='province',
            field=models.CharField(db_index=True, default='Tehran', max_length=100),
        ),
    ]
