# Generated by Django 5.2 on 2026-07-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='active', max_length=16),
        ),
    ]
